In [1]:
import csv
import heapq
import numpy as np
import pandas as pd

In [2]:
k = 2

df = pd.read_csv('salario.csv')

In [170]:
salario_2 = df.drop('salario', axis=1)
#salario_2 = salario_2.drop('id',axis=1)
salario_2 = salario_2[0:50]

In [171]:
salario_2.data.unique().shape

(50,)

In [172]:
dt2 = []
dt2 = salario_2["data"].str.split("/", n = 2, expand = True)
salario_2 = salario_2.drop("data", axis=1)

In [173]:
salario_2['dia'] = dt2[0]
salario_2['mes'] = dt2[1]
salario_2['ano'] = dt2[2]

In [174]:
salario_2

,id,pais,estado,cidade,genero,dia,mes,ano
0,1,United States,Alabama,Mobile,Male,10,01,1987
1,2,Portugal,Porto,Rego,Male,29,11,2007
2,3,Sweden,Kalmar,Emmaboda,Male,23,06,1984
3,4,Sweden,Västmanland,Sala,Female,04,11,1983
4,5,France,Bretagne,Quimperlé,Female,18,11,1990
5,6,United States,Ohio,Cincinnati,Female,10,07,1981
6,7,France,Poitou-Charentes,Niort,Female,23,03,1989
7,8,Mexico,Tamaulipas,Del Valle,Male,02,05,1990
8,9,United States,Oklahoma,Oklahoma City,Male,27,11,1992
9,10,France,Champagne-Ardenne,Reims,Female,19,01,2007
10,11,United States,Florida,Melbourne,Male,29,01,2007
11,12,Sweden,Värmland,Årjäng,Male,25,03,1995
12,13,Sweden,Uppsala,Uppsala,Female,15,01,1996
13,14,Sweden,Södermanland,Katrineholm,Female,31,10,2002
14,15,United States,Kentucky,Frankfort,Female,14,11,1980
15,16,Sweden,Stockholm,Älvsjö,Female,05,05,1985
16,17,Canada,Manitoba,Thompson,Male,30,04,2009
17,18,United States,Alabama,Mobile,Female,06,05,1983
18,19,Mexico,Veracruz Llave,Morelos,Male,09,11,2004
19,20,Sweden,Dalarna,Avesta,Female,04,05,2000
20,21,Sweden,Kalmar,Nybro,Female,28,02,1996
21,22,United States,Texas,Corpus Christi,Male,06,01,1999
22,23,United Kingdom,England,Church End,Male,27,04,1992
23,24,France,Haute-Normandie,Rouen,Male,20,09,2002
24,25,France,Pays de la Loire,Nantes,Female,21,11,1990
25,26,Sweden,Västernorrland,Kvissleby,Male,19,10,1981
26,27,Sweden,Västra Götaland,Göteborg,Male,01,12,2000
27,28,Portugal,Portalegre,Santo Aleixo,Male,25,10,1999
28,29,France,Franche-Comté,Besançon,Male,19,04,1994
29,30,Sweden,Stockholm,Gustavsberg,Female,16,08,1999
30,31,Mexico,Veracruz Llave,Lindavista,Female,09,03,2000
31,32,France,Bretagne,Vannes,Male,03,02,1992
32,33,Portugal,Porto,Guimarei,Female,18,04,1996
33,34,Sweden,Skåne,Ystad,Female,17,09,1999
34,35,Sweden,Västra Götaland,Göteborg,Male,30,12,1997
35,36,Portugal,Castelo Branco,Aranhas,Female,03,04,1981
36,37,Portugal,Setúbal,Santana,Male,01,06,2000
37,38,Portugal,Porto,Fojo,Female,29,05,1981
38,39,United States,Kentucky,Louisville,Female,26,10,1993
39,40,Portugal,Aveiro,Canedo,Male,23,12,1999
40,41,Portugal,Viana do Castelo,Viso,Female,12,01,2005
41,42,Portugal,Vila Real,Mondim de Basto,Female,18,08,1981
42,43,Sweden,Skåne,Ängelholm,Female,28,06,2004
43,44,Sweden,Stockholm,Sundbyberg,Female,17,03,2000
44,45,Portugal,Vila Real,Amieiro,Female,25,02,2008
45,46,Portugal,Braga,Agra,Male,29,04,1997
46,47,Portugal,Santarém,Barrosa,Female,17,01,1981
47,48,France,Île-de-France,Paris 10,Female,15,01,2004
48,49,France,Centre,Tours,Male,18,07,2010
49,50,Sweden,Gävleborg,Gävle,Female,29,09,1985

In [192]:
def distance(reg1, reg2):
    count = 0
    for i in range(1, reg1.shape[0]):
        if(reg1[i]!=reg2[i]):
            count = count + 1
    return count

In [176]:
#distance(salario_2.loc[[0]], salario_2.loc[[1]])

In [177]:
salario_2.loc[(df['cidade']) == 'Mobile']

    id           pais   estado  cidade  genero dia mes   ano
0    1  United States  Alabama  Mobile    Male  10  01  1987
17  18  United States  Alabama  Mobile  Female  06  05  1983

In [178]:
#cidades = pd.DataFrame(data=salario_2.cidade.unique())
#estados = pd.DataFrame(data=salario_2.estado.unique())
#paises = pd.DataFrame(data=salario_2.pais.unique())

In [185]:
def ordenarDist(df):
    distances = []
    for i in range(0, df.shape[0]):
        for j in range(i+1,df.shape[0]-1):
            dis = distance(df.loc[[i]],df.loc[[j]])
            distances.append([dis, i, j])
    distances_Ord = sorted(distances)
    return distances_Ord

In [186]:
orden = ordenarDist(salario_2)[0]
len(orden)

   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
   id           pais   estado  cidade genero dia mes   ano

0   1  United States  Alabama  Mobile   Male  10  01  1987
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
   id           pais   estado  cidade genero dia mes   ano
0   1  United States  Alabama  Mobile   Male  10  01  1987
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992

   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
   id      pais estado cidade genero dia mes   ano
1   2  Portugal  Porto   Rego   Male  29  11  2007
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais           estado    cidade genero dia mes   ano

26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
   id    pais  estado    cidade genero dia mes   ano
2   3  Sweden  Kalmar  Emmaboda   Male  23  06  1984
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais  estado cidade  genero dia mes   ano

20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
   id    pais       estado cidade  genero dia mes   ano
3   4  Sweden  Västmanland   Sala  Female  04  11  1983
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990

    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
   id    pais    estado     cidade  genero dia mes   ano
4   5  France  Bretagne  Quimperlé  Female  18  11  1990
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
   id    pais             estado cidade  genero dia mes   ano

9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
   id           pais estado      cidade  genero dia mes   ano
5   6  United States   Ohio  Cincinnati  Female  10  07  1981
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990

   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
   id    pais            estado cidade  genero dia mes   ano
6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
   id    pais            estado cidade  genero dia mes   ano

6   7  France  Poitou-Charentes  Niort  Female  23  03  1989
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id      pais    estado   cidade  genero dia mes   ano

46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
   id    pais      estado     cidade genero dia mes   ano
7   8  Mexico  Tamaulipas  Del Valle   Male  02  05  1990
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id      pais    estado   cidade  genero dia mes   ano

46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
   id           pais    estado         cidade genero dia mes   ano
8   9  United States  Oklahoma  Oklahoma City   Male  27  11  1992
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
   id    pais             estado cidade  genero dia mes   ano
9  10  France  Champagne-Ardenne  Reims  Female  19  01  2007

    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id           pais   estado     cidade genero dia mes   ano
10  11  United States  Florida  Melbourne   Male  29  01  2007
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002

    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais    estado  cidade genero dia mes   ano
11  12  Sweden  Värmland  Årjäng   Male  25  03  1995
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id           pais   estado  cidade  genero dia mes   ano

17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais   estado   cidade  genero dia mes   ano
12  13  Sweden  Uppsala  Uppsala  Female  15  01  1996
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992

    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais        estado       cidade  genero dia mes   ano
13  14  Sweden  Södermanland  Katrineholm  Female  31  10  2002
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980

    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id           pais    estado     cidade  genero dia mes   ano
14  15  United States  Kentucky  Frankfort  Female  14  11  1980
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997

    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais     estado  cidade  genero dia mes   ano
15  16  Sweden  Stockholm  Älvsjö  Female  05  05  1985
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais    estado    cidade genero dia mes   ano

16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais    estado    cidade genero dia mes   ano
16  17  Canada  Manitoba  Thompson   Male  30  04  2009
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id           pais   estado  cidade  genero dia mes   ano
17  18  United States  Alabama  Mobile  Female  06  05  1983
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000

    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais          estado   cidade genero dia mes   ano
18  19  Mexico  Veracruz Llave  Morelos   Male  09  11  2004
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992

    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais   estado  cidade  genero dia mes   ano
19  20  Sweden  Dalarna  Avesta  Female  04  05  2000
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008

    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais  estado cidade  genero dia mes   ano
20  21  Sweden  Kalmar  Nybro  Female  28  02  1996
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id           pais estado          cidade genero dia mes   ano
21  22  United States  Texas  Corpus Christi   Male  06  01  1999
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992

    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id            pais   estado      cidade genero dia mes   ano
22  23  United Kingdom  England  Church End   Male  27  04  1992
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981

    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais           estado cidade genero dia mes   ano
23  24  France  Haute-Normandie  Rouen   Male  20  09  2002
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais            estado  cidade  genero dia mes   ano
24  25  France  Pays de la Loire  Nantes  Female  21  11  1990
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981

    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais          estado     cidade genero dia mes   ano
25  26  Sweden  Västernorrland  Kvissleby   Male  19  10  1981
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais           estado    cidade genero dia mes   ano
26  27  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id      pais  estado  cidade genero dia mes   ano

39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id      pais      estado        cidade genero dia mes   ano
27  28  Portugal  Portalegre  Santo Aleixo   Male  25  10  1999
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais         estado    cidade genero dia mes   ano
28  29  France  Franche-Comté  Besançon   Male  19  04  1994
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005

    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais     estado       cidade  genero dia mes   ano
29  30  Sweden  Stockholm  Gustavsberg  Female  16  08  1999
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais          estado      cidade  genero dia mes   ano
30  31  Mexico  Veracruz Llave  Lindavista  Female  09  03  2000
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997

    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais    estado  cidade genero dia mes   ano
31  32  France  Bretagne  Vannes   Male  03  02  1992
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id      pais estado    cidade  genero dia mes   ano
32  33  Portugal  Porto  Guimarei  Female  18  04  1996
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais estado cidade  genero dia mes   ano
33  34  Sweden  Skåne  Ystad  Female  17  09  1999
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005

    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais           estado    cidade genero dia mes   ano
34  35  Sweden  Västra Götaland  Göteborg   Male  30  12  1997
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id      pais          estado   cidade  genero dia mes   ano
35  36  Portugal  Castelo Branco  Aranhas  Female  03  04  1981
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id      pais   estado   cidade genero dia mes   ano
36  37  Portugal  Setúbal  Santana   Male  01  06  2000
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981

    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id      pais estado cidade  genero dia mes   ano
37  38  Portugal  Porto   Fojo  Female  29  05  1981
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id           pais    estado      cidade  genero dia mes   ano
38  39  United States  Kentucky  Louisville  Female  26  10  1993
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id      pais  estado  cidade genero dia mes   ano
39  40  Portugal  Aveiro  Canedo   Male  23  12  1999
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id      pais            estado cidade  genero dia mes   ano
40  41  Portugal  Viana do Castelo   Viso  Female  12  01  2005
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id      pais     estado           cidade  genero dia mes   ano
41  42  Portugal  Vila Real  Mondim de Basto  Female  18  08  1981
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais     estado      cidade  genero dia mes   ano

43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais estado     cidade  genero dia mes   ano
42  43  Sweden  Skåne  Ängelholm  Female  28  06  2004
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais     estado      cidade  genero dia mes   ano
43  44  Sweden  Stockholm  Sundbyberg  Female  17  03  2000
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id      pais     estado   cidade  genero dia mes   ano
44  45  Portugal  Vila Real  Amieiro  Female  25  02  2008
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id      pais estado cidade genero dia mes   ano
45  46  Portugal  Braga   Agra   Male  29  04  1997
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id      pais    estado   cidade  genero dia mes   ano
46  47  Portugal  Santarém  Barrosa  Female  17  01  1981
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010
    id    pais         estado    cidade  genero dia mes   ano
47  48  France  Île-de-France  Paris 10  Female  15  01  2004
    id    pais  estado cidade genero dia mes   ano
48  49  France  Centre  Tours   Male  18  07  2010

3

In [231]:
def clusters(k, df):
    df = np.array(df)
    clusters = []
    for i in range(0, df.shape[0]-1):
        if(i+1 in df[:,0]):
            distances = []
            cluster = [i]
            for j in range(i+1,df.shape[0]):
                if(j+1 in df[:,0]):
                    dis = distance(df[i],df[j])
                    distances.append([dis, i, j])
            distances = sorted(distances)
            df = np.delete(df, i, 0)
            #print(df)
            for j in range(0, k-1):
                #print(distances[j])
                cluster.append(distances[j][2])
                df = np.delete(df, distances[j][2]-2, 0)
                #print(df)
        clusters.append(cluster)
        print(clusters)
        #print(distances)
    #print(clusters)
    #distances_Ord = sorted(distances)
    #return distances_Ord

In [232]:
clusters(k, salario_2)

[[0, 10]]
[[0, 10], [1, 18]]
[[0, 10], [1, 18], [1, 18]]
[[0, 10], [1, 18], [1, 18], [3, 11]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12], [6, 12]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12], [6, 12], [6, 12]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12], [6, 12], [6, 12], [10, 32]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12], [6, 12], [6, 12], [10, 32], [11, 17]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12], [6, 12], [6, 12], [10, 32], [11, 17], [11, 17]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12], [6, 12], [6, 12], [10, 32], [11, 17], [11, 17], [11, 17]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12], [6, 12], [6, 12], [10, 32], [11, 17], [11, 17], [11, 17], [14, 21]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12], [6, 12], [6, 12], [10, 32], [11, 17], [11, 17], [11, 17], [14, 21], [15, 16]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12], [6, 12], [6, 12], [10, 32], [11, 17], [11, 17], [11, 17], [14, 21], [15, 16], [16, 23]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12], [6, 12], [6, 12], [10, 32], [11, 17], [11, 17], [11, 17], [14, 21], [15, 16], [16, 23], [17, 21]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12], [6, 12], [6, 12], [10, 32], [11, 17], [11, 17], [11, 17], [14, 21], [15, 16], [16, 23], [17, 21], [17, 21]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12], [6, 12], [6, 12], [10, 32], [11, 17], [11, 17], [11, 17], [14, 21], [15, 16], [16, 23], [17, 21], [17, 21], [17, 21]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12], [6, 12], [6, 12], [10, 32], [11, 17], [11, 17], [11, 17], [14, 21], [15, 16], [16, 23], [17, 21], [17, 21], [17, 21], [17, 21]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12], [6, 12], [6, 12], [10, 32], [11, 17], [11, 17], [11, 17], [14, 21], [15, 16], [16, 23], [17, 21], [17, 21], [17, 21], [17, 21], [21, 24]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12], [6, 12], [6, 12], [10, 32], [11, 17], [11, 17], [11, 17], [14, 21], [15, 16], [16, 23], [17, 21], [17, 21], [17, 21], [17, 21], [21, 24], [21, 24]]
[[0, 10], [1, 18], [1, 18], [3, 11], [4, 6], [4, 6], [6, 12], [6, 12], [6, 12], [6, 12], [10, 32], [11, 17], [11, 17], [11, 17], [14, 21], [15, 16], [16, 23], [17, 21], [17, 21], [17, 21], [17, 21], [21, 24], [21, 24], [23, 24]]

IndexError: index 24 is out of bounds for axis 0 with size 24

In [73]:
g_date = {
    'ano': "****",
    'mes': "**",
    'dia': "**"
}

g_local = {
    'pais': "*",
    'estado': "*",
    'cidade': "*"
}

g_gender = {
    'genero': "*"
}

In [81]:
def k_anonimity(k, dist_ord):
    for i in len(dist_ord[0]):

SyntaxError: unexpected EOF while parsing (<ipython-input-81-329a226f0a64>, line 3)

In [66]:
print(salario_2.loc[[orden[1]]])
print(salario_2.loc[[orden[2]]])

      pais           estado    cidade genero dia mes   ano
26  Sweden  Västra Götaland  Göteborg   Male  01  12  2000
      pais           estado    cidade genero dia mes   ano
34  Sweden  Västra Götaland  Göteborg   Male  30  12  1997

In [53]:
#similar = salario_2.loc[(df['cidade']) == cidades[0][0]]
#re = similar.loc[0]

pais      United States
estado          Alabama
cidade           Mobile
genero             Male
dia                  10
mes                  01
ano                1987
Name: 0, dtype: object